Update client.py and README.md
mwalsh161/ModuleServer pull request #3
Opened 2020-01-14 03:17 UTC by cpeng365

client.py
1. Added function get_modules in client.py
2. Removed all strip() for response
3. Replaced all tabs with spaces
4. Added private helper function __handshake() that opens the socket, sends the handshake, and closes the socket

README.md
1. Added section for clients

2020-01-15 14:36 UTC, mwalsh161 requested changes
A few minor comments:
 - In readme, if you refer to names of those functions as "methods" you can omit the `self` arg.
 - A few var naming suggestions
 - Compare expected var contents/print output
 - Small change to `__handshake` will make it usable in `com` as well.

2020-01-15 14:36 UTC, mwalsh161 commented on README.md
> +client_1 = client()
let's add `'localhost'` as the argument (even though it is default). On a separate question, is the argument name in client's `__init__` method called `host`. If not, can we change it to that? If it is, let's explicitly say here `host = 'localhost'`.

2020-01-15 14:36 UTC, mwalsh161 commented on README.md
> +client_1 = client()
Also superrrrrr nitpicky - can we change `client_1` to `myclient` or something similar?

2020-01-15 14:36 UTC, mwalsh161 commented on README.md
> +ping(self) can be issued to ping the server to get the client's IP address and binding port.
No need to include the `self` in docs - it is always assumed. Instead let's say "The `ping()` method can be..."

2020-01-15 14:36 UTC, mwalsh161 commented on README.md
> +com(self, module, funcname, *args) can be called to communicate with a module and request it to perform a function. Here is an example of requesting "moduleB" to call "fun1" with arguments ['ay', 1,
same comment here as above, you can omit `self`, especially if you call it a "method"

2020-01-15 14:36 UTC, mwalsh161 commented on README.md
> +resp = client_1.com('moduleB', 'fun1', 'ay', 1, False, None)
Is this the `moduleB` from above? If so, can you also print the expected output/contents of `resp` so users can compare.

2020-01-15 14:36 UTC, mwalsh161 commented on client.py
>      def __init__(self,ip=DEFAULT_IP,port=DEFAULT_PORT):
As per above comment, let's change `ip` to `host` since host can mean host *name* or IP.

2020-01-15 14:36 UTC, mwalsh161 commented on client.py
> +    def __handshake(self,handshake):
is this used in the `com` method? It could be if you conditionally leave the socket open based on perhaps another input arg.

2020-01-16 00:07 UTC, cpeng365 commented
Should all be fixed now! Let me know if there is anything I can change.

2020-01-21 17:28 UTC, merged

2020-01-21 17:32 UTC, mwalsh161 commented
- Made a few relatively large bug fixes.
 - Decided it would be best to add numpy style docstrings since this file will be used more frequently by users.
- Fixed up logging to be configured by users rather than hardcoded.
- Tested on python 2 and 3.